import os
import re
from typing import List

from ..core import BaseRule, ValidationContext, RuleResult

class NoHardcodedTablesRule(BaseRule):
    """
    Ensures that a specific file does not contain hardcoded tables.
    Tables should be imported using \\input{} to enforce reproducibility.
    """
    def __init__(self, file_path: str):
        self.file_path = file_path
        
    @property
    def name(self) -> str:
        return f"NoHardcodedTablesRule({self.file_path})"
        
    @property
    def description(self) -> str:
        return "Ensures tables are not hardcoded but imported dynamically."
        
    def validate(self, context: ValidationContext) -> RuleResult:
        result = RuleResult(RuleResult.PASS)
        content = context.get_file_content(self.file_path)
        
        if not content:
            return result
            
        # Remove commented out sections
        content_no_comments = re.sub(r'%.*$', '', content, flags=re.MULTILINE)
        
        if r'\begin{tabular}' in content_no_comments:
            result.add_error(f"[{self.file_path}] Hardcoded \\begin{{tabular}} found. Tables should be generated by scripts and imported via \\input{{}}.")
            
        return result


class CiteVerificationRule(BaseRule):
    """
    Extracts all citations used in the document and verifies that they exist
    in the bibliography file.
    """
    def __init__(self, tex_files: List[str], bib_file: str):
        self.tex_files = tex_files
        self.bib_file = bib_file
        
    @property
    def name(self) -> str:
        return "CiteVerificationRule"
        
    @property
    def description(self) -> str:
        return "Ensures every citation exists in the .bib file."
        
    def validate(self, context: ValidationContext) -> RuleResult:
        result = RuleResult(RuleResult.PASS)
        
        bib_content = context.get_file_content(self.bib_file)
        if not bib_content:
            result.add_error(f"Bibliography file {self.bib_file} not found.")
            return result
            
        # Parse bibtex keys: e.g. @article{2020_Author,
        # regex to capture the key: @\w+\s*\{\s*([^,]+),
        bib_keys = set(re.findall(r'@\w+\s*\{\s*([^,]+),', bib_content))
        
        # Parse all citations in all tex files
        cited_keys = set()
        for tex_file in self.tex_files:
            content = context.get_file_content(tex_file)
            content_no_comments = re.sub(r'%.*$', '', content, flags=re.MULTILINE)
            # Find \cite{key}, \citep{key1,key2}, \citet{key}
            cites = re.findall(r'\\cite[pt]*\s*\{([^}]+)\}', content_no_comments)
            for cite_block in cites:
                for key in cite_block.split(','):
                    cited_keys.add(key.strip())
                    
        for key in cited_keys:
            if key not in bib_keys:
                result.add_error(f"Citation key '{key}' is used in the text but not defined in {self.bib_file}.")
                
        return result


class OrphanLabelRule(BaseRule):
    """
    Ensures that every \\label{} defined in the document is referenced somewhere 
    using \\ref{}.
    """
    def __init__(self, tex_files: List[str]):
        self.tex_files = tex_files
        
    @property
    def name(self) -> str:
        return "OrphanLabelRule"
        
    @property
    def description(self) -> str:
        return "Ensures every \\label is referenced by a \\ref."
        
    def validate(self, context: ValidationContext) -> RuleResult:
        result = RuleResult(RuleResult.PASS)
        
        all_labels = set()
        all_refs = set()
        
        for tex_file in self.tex_files:
            content = context.get_file_content(tex_file)
            content_no_comments = re.sub(r'%.*$', '', content, flags=re.MULTILINE)
            
            labels = re.findall(r'\\label\s*\{([^}]+)\}', content_no_comments)
            refs = re.findall(r'\\ref\s*\{([^}]+)\}', content_no_comments)
            
            all_labels.update(labels)
            all_refs.update(refs)
            
        for label in all_labels:
            if label not in all_refs:
                result.add_error(f"Label '{label}' is defined but never referenced.")
                
        return result


class EquationEnvironmentRule(BaseRule):
    """
    Prohibits the use of unnumbered equations ($$ ... $$ or \\begin{equation*})
    in the specified files.
    """
    def __init__(self, tex_files: List[str]):
        self.tex_files = tex_files
        
    @property
    def name(self) -> str:
        return "EquationEnvironmentRule"
        
    @property
    def description(self) -> str:
        return "Ensures all display equations are properly numbered."
        
    def validate(self, context: ValidationContext) -> RuleResult:
        result = RuleResult(RuleResult.PASS)
        
        for tex_file in self.tex_files:
            content = context.get_file_content(tex_file)
            content_no_comments = re.sub(r'%.*$', '', content, flags=re.MULTILINE)
            
            if '$$' in content_no_comments:
                result.add_error(f"[{tex_file}] Found '$$'. Use \\begin{{equation}} for numbered display equations.")
            if r'\begin{equation*}' in content_no_comments:
                result.add_error(f"[{tex_file}] Found unnumbered equation*. Use \\begin{{equation}}.")
                
        return result


class LiteraturePDFNamingRule(BaseRule):
    """
    Ensures that every PDF inside the literature folder matches a citation key in the .bib file.
    """
    def __init__(self, lit_folder: str, bib_file: str):
        self.lit_folder = lit_folder
        self.bib_file = bib_file
        
    @property
    def name(self) -> str:
        return "LiteraturePDFNamingRule"
        
    @property
    def description(self) -> str:
        return f"Ensures PDFs in {self.lit_folder} match keys in {self.bib_file}."
        
    def validate(self, context: ValidationContext) -> RuleResult:
        result = RuleResult(RuleResult.PASS)
        
        # Load bib keys
        # We need to compute absolute paths since bib is likely in a different dir
        # context.get_file_content expects a path relative to context.target_dir.
        # But this rule crosses directories. The target_dir is usually 5_manuscript_tesis.
        # lit_folder is usually ../1_literature/papers
        bib_content = context.get_file_content(self.bib_file)
        if not bib_content:
            result.add_error(f"Bibliography file {self.bib_file} not found.")
            return result
            
        bib_keys = set(re.findall(r'@\w+\s*\{\s*([^,]+),', bib_content))
        
        # Scan PDFs
        pdf_files = context.glob_files(os.path.join(self.lit_folder, "**/*.pdf"))
        
        for pdf in pdf_files:
            basename = os.path.basename(pdf)
            # ignore files like supplementary.pdf
            if "supplementary" in basename.lower() or "estado_de_arte" in basename.lower() or "metodologia" in basename.lower() or "pmulti" in basename.lower():
                continue
                
            key = basename.replace('.pdf', '')
            if key not in bib_keys:
                result.add_error(f"PDF file '{basename}' in literature folder does not match any citation key in {self.bib_file}.")
                
        return result
